version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: LjNiW/ZWrfVIJn3Mc9foeg==
  DOCKER_PASS:
    secure: 4gsl5WiqIztEWhL5fuhp9X0qT/mKg9fYzKYUUPf5WStIuNddv0fvIKGmvvyuFzzd

build_script:
  - ps: .\appveyor-build.ps1

test_script:
  - ps: .\appveyor-test.ps1

deploy_script:
  - ps: >-
      if (Test-Path Env:\APPVEYOR_REPO_TAG_NAME) {

        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

        .\appveyor-deploy.ps1

      }
